version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - golang

exclude_paths:
  - vendor/
  - gps/_testdata
  - cmd/dep/testdata
  - testdata
  - gps/internal/pb
