include:
  - project: "widas/software-quality/gitlab-template-projects/widas-ci-templates"
    file: "golang/go-lib.yml"

stages:
  - test
  - update-version
  - release

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.5
