include:
  - project: "widas/software-quality/gitlab-template-projects/widas-customer-ci-templates"
    file: "golang/go-lib.yml"

stages:
  - prepare
  - test
  - release

acceptance_test:
  image: golang:1.21.0
  stage: test
  before_script:
    - echo "machine gitlab.widas.de login $GITLAB_LOGIN password $GITLAB_TOKEN" > ~/.netrc
  script:
    - export TERRAFORM_PROVIDER_CIDAAS_CLIENT_ID=$CI_ID TERRAFORM_PROVIDER_CIDAAS_CLIENT_SECRET=$CI_SECRET
    - make test-ci
  coverage: '/total:\s+\(statements\)\s+(\d+(?:\.\d+)?%)/'
  artifacts:
    paths:
      - coverage.html
