include:
  - project: "widas/software-quality/gitlab-template-projects/widas-customer-ci-templates"
    file: "golang/go-lib.yml"
    ref: golang-version-update

stages:
  - prepare
  - test
  - release

get_prereqiusites:
  stage: prepare
  only:
    - never

acceptance_test:
  image: golang:1.24.4
  stage: test
  before_script:
    - echo "machine gitlab.widas.de login $GITLAB_LOGIN password $GITLAB_TOKEN" > ~/.netrc
  script:
    - export TERRAFORM_PROVIDER_CIDAAS_CLIENT_ID=$CI_ID TERRAFORM_PROVIDER_CIDAAS_CLIENT_SECRET=$CI_SECRET BASE_URL=$BASE_URL
    - make test-ci
  coverage: '/total:\s+\(statements\)\s+(\d+(?:\.\d+)?%)/'
  artifacts:
    paths:
      - coverage.html

dependency_scanning:
  image: golang:1.24.4

# get_version is not required as we don't create tag by CI anymore
get_version:
  stage: prepare
  only:
    - never

# Manually create releases for better changelog and tag maintenance.
release:
  stage: release
  only:
    - never
