include:
  - project: 'widas/software-quality/gitlab-template-projects/widas-ci-templates'
    file: 'golang/go-lib.yml'

stages:
  - test
  - update-version
  - release

code_quality_json:
  stage: test
  image: docker
  allow_failure: true
  variables:
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest"
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    - docker run
      --env SOURCE_CODE="$PWD"
      --env CODECLIMATE_CODE="$PWD/app"
      --volume /tmp/cc:/tmp/cc
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "$CODE_QUALITY_IMAGE" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
  dependencies: []
