variable "common_configs" {
  type = object({
    client_type         = optional(string)
    company_name        = optional(string)
    company_address     = optional(string)
    company_website     = optional(string)
    allowed_scopes      = optional(list(string))
    redirect_uris       = optional(list(string))
    allowed_logout_urls = optional(list(string))
    allowed_groups = optional(list(object({
      group_id      = string
      roles         = list(string)
      default_roles = list(string)
    })))
    primary_color                   = optional(string)
    media_type                      = optional(string)
    content_align                   = optional(string)
    allow_login_with                = optional(list(string))
    enable_deduplication            = optional(bool)
    auto_login_after_register       = optional(bool)
    enable_passwordless_auth        = optional(bool)
    register_with_login_information = optional(bool)
    allow_disposable_email          = optional(bool)
    validate_phone_number           = optional(bool)
    fds_enabled                     = optional(bool)
    hosted_page_group               = optional(string)
    client_display_name             = optional(string)
    response_types                  = optional(list(string))
    grant_types                     = optional(list(string))
    login_providers                 = optional(list(string))
    additional_access_token_payload = optional(list(string))
    required_fields                 = optional(list(string))
    is_hybrid_app                   = optional(bool)
    allowed_web_origins             = optional(list(string))
    allowed_origins                 = optional(list(string))
    mobile_settings = optional(object({
      team_id      = optional(string)
      bundle_id    = optional(string)
      package_name = optional(string)
      key_hash     = optional(string)
    }))
    default_max_age                   = optional(number)
    token_lifetime_in_seconds         = optional(number)
    id_token_lifetime_in_seconds      = optional(number)
    refresh_token_lifetime_in_seconds = optional(number)
    template_group_id                 = optional(string)
    client_id                         = optional(string)
    client_secret                     = optional(string)
    saml_providers = optional(list(object({
      provider_name       = string
      display_name        = string
      logo_url            = optional(string)
      type                = string
      is_provider_visible = optional(bool)
      domains             = optional(list(string))
    })))
    ad_providers = optional(list(object({
      provider_name       = string
      display_name        = string
      logo_url            = optional(string)
      type                = string
      is_provider_visible = optional(bool)
      domains             = optional(list(string))
    })))
    jwe_enabled  = optional(bool)
    user_consent = optional(bool)
    operations_allowed_groups = optional(list(object({
      group_id      = string
      roles         = list(string)
      default_roles = list(string)
    })))
    enabled                             = optional(bool)
    allowed_fields                      = optional(list(string))
    always_ask_mfa                      = optional(bool)
    smart_mfa                           = optional(bool)
    allowed_mfa                         = optional(list(string))
    captcha_ref                         = optional(string)
    captcha_refs                        = optional(list(string))
    consent_refs                        = optional(list(string))
    communication_medium_verification   = optional(string)
    email_verification_required         = optional(bool)
    mobile_number_verification_required = optional(bool)
    allowed_roles                       = optional(list(string))
    default_roles                       = optional(list(string))
    enable_classical_provider           = optional(bool)
    is_remember_me_selected             = optional(bool)
    enable_bot_detection                = optional(bool)
    bot_provider                        = optional(string)
    allow_guest_login_groups = optional(list(object({
      group_id      = string
      roles         = list(string)
      default_roles = list(string)
    })))
    is_login_success_page_enabled    = optional(bool)
    is_register_success_page_enabled = optional(bool)
    group_ids                        = optional(list(string))
    is_group_login_selection_enabled = optional(bool)
    group_selection = optional(object({
      always_show_group_selection = optional(bool)
      selectable_groups           = optional(list(string))
      selectable_group_types      = optional(list(string))
    }))
    group_types                     = optional(list(string))
    backchannel_logout_uri          = optional(string)
    post_logout_redirect_uris       = optional(list(string))
    userinfo_signed_response_alg    = optional(string)
    userinfo_encrypted_response_alg = optional(string)
    userinfo_encrypted_response_enc = optional(string)
    request_object_signing_alg      = optional(string)
    request_object_encryption_alg   = optional(string)
    request_object_encryption_enc   = optional(string)
    request_uris                    = optional(list(string))
    description                     = optional(string)
    default_scopes                  = optional(list(string))
    pending_scopes                  = optional(list(string))
    consent_page_group              = optional(string)
    password_policy_ref             = optional(string)
    blocking_mechanism_ref          = optional(string)
    sub                             = optional(string)
    role                            = optional(string)
    mfa_configuration               = optional(string)
    suggest_mfa                     = optional(list(string))
    login_spi = optional(object({
      oauth_client_id = optional(string)
      spi_url         = optional(string)
    }))
    background_uri        = optional(string)
    video_url             = optional(string)
    bot_captcha_ref       = optional(string)
    application_meta_data = optional(map(string))
    allow_guest_login     = optional(bool)
    group_role_restriction = optional(object({
      match_condition = optional(string)
      filters = optional(list(object({
        group_id = string
        role_filter = object({
          match_condition = string
          roles           = list(string)
        })
      })))
    }))
    basic_settings = optional(object({
      client_secrets = optional(list(object({
        client_secret            = optional(string)
        client_secret_expires_at = optional(number)
      })))
    }))
    mfa = optional(object({
      setting                  = optional(string)
      time_interval_in_seconds = optional(number)
      allowed_methods          = optional(list(string))
    }))
    social_providers = optional(list(object({
      provider_name = optional(string)
      social_id     = optional(string)
    })))
    custom_providers = optional(list(object({
      provider_name       = optional(string)
      display_name        = optional(string)
      logo_url            = optional(string)
      type                = optional(string)
      is_provider_visible = optional(bool)
      domains             = optional(list(string))
    })))
    accent_color                        = optional(string)
    logo_align                          = optional(string)
    webfinger                           = optional(string)
    require_auth_time                   = optional(bool)
    enable_login_spi                    = optional(bool)
    backchannel_logout_session_required = optional(bool)
    suggest_verification_methods = optional(object({
      mandatory_config = optional(object({
        methods    = optional(list(string))
        range      = optional(string)
        skip_until = optional(string)
      }))
      optional_config = optional(object({
        methods = optional(list(string))
      }))
      skip_duration_in_days = optional(number)
    }))
    policy_uri                      = optional(string)
    tos_uri                         = optional(string)
    imprint_uri                     = optional(string)
    contacts                        = optional(list(string))
    token_endpoint_auth_method      = optional(string)
    token_endpoint_auth_signing_alg = optional(string)
    default_acr_values              = optional(list(string))
    editable                        = optional(bool)
    web_message_uris                = optional(list(string))
  })
  default = {}
}
